[project]
name = "autocomp"
version = "0.1.1"
authors = [
    { name="charleshong3", email="charleshong@berkeley.edu" },
]
description = "Automation compilation for diverse hardware backends ."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10.0"
dependencies = [
    "openai",
    "google-generativeai",
    "anthropic",
    "numpy",
    "pandas",
    "wandb",
    "backoff",
    "mistralai[gcp]>=1.0.0",
    "together",
]

[project.urls]
"Homepage" = "https://github.com/ucb-bar/autocomp"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["prompts", "autocomp"]
