from autocomp.hw_config.hardware_config import HardwareConfig
from autocomp.hw_config.cuda_config import CudaHardwareConfig
from autocomp.hw_config.gemmini_config import GemminiHardwareConfig
from autocomp.hw_config.trn_config import TrnHardwareConfig
